### ISSUE TITLE
SG Detection On Custom Images

### ISSUE THREAD

**Issue by draym28** [mlvlab/SpeaQ#1]
Hi, you have done a great job!

Can you provide the code or examples for using SpeaQ to conduct SG Detection on custom images?

**Comment by jonghakim35** [comment]
Hi, thanks for your interest to our work.

Unfortunately, I currently have other ongoing projects, so I won’t be able to spare time for implementing the visualization for custom images.
I may update the visualization for custom images when I have some free time and will notify you later on, but I can't promise exactly when that will be.
If you are in a rush, I suggest you to implement the feature yourself.
Since the code is based on Detectron, if you implement the dataloader yourself, there shouldn’t be much difficulty with visualization.

**Comment by draym28** [comment]
Thanks for your reply!
