### ISSUE TITLE
Training initial weight for SpeaQ

### ISSUE THREAD

**Issue by fujiawei0724** [mlvlab/SpeaQ#5]
Thanks for the great work and code base. I am curious about how you train the initial weight (detr weight to initialize speaq model). When I want to train it by myself, it reports this bug: 
<img width="976" alt="Screenshot 2024-08-04 at 21 44 47" src="https://github.com/user-attachments/assets/7e42b28c-57e3-4e7c-ac98-064f5fb77bb3">
It seems that the training process is unstable, I want to know how to train the model and get this initial weight for detr. Thanks for your help, looking forward to your reply.

**Comment by jonghakim35** [comment]
Hi, thanks for your interest in our work.

As mentioned in the README, we utilized the pre-trained DETR weights provided in **[this repository](https://github.com/ubc-vision/IterativeSG)** rather than training the model ourselves. 
Therefore, for detailed information about the training process, it would be best to consult the original authors. 
Additionally, you may find relevant information in **[this issue thread](https://github.com/ubc-vision/IterativeSG/issues/3)** of the original repository.
